# Generated by Django 5.0.6 on 2024-06-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_date_post_creation_date_remove_post_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='date',
        ),
    ]
