# Generated by Django 5.0.6 on 2024-06-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_creation_date_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.CharField(default='', max_length=75),
        ),
    ]
